# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: var setup
        run: |
          PRJID=$(curl -k -u fdadmin:fz#n1vTeHRNQy^9C -H "Content-Type: application/json" -X GET "http://srvld20.noesis.pt/flexdeploy/rest/v1/project?projectName=OracleDB" | jq '.[] | .projectId')
          echo "PRJID=$PRJID"

          STRMID=$(curl -k -s -u fdadmin:fz#n1vTeHRNQy^9C -H "Content-Type: application/json"  http://srvld20.noesis.pt/flexdeploy/rest/v1/project/$PRJID/stream?streamName=main | jq '.[] | .streamId')
          echo "STRMID=$STRMID"

          BUILDENVID=$(curl -k -s -u fdadmin:fz#n1vTeHRNQy^9C -H "Content-Type: application/json" http://srvld20.noesis.pt/flexdeploy/rest/v1/topology/environment?environmentName=Development | jq '.[] | .environmentId')
          echo "BUILDENVID=$BUILDENVID"

          DEPLOYENVID=$(curl -k -s -u fdadmin:fz#n1vTeHRNQy^9C -H "Content-Type: application/json" http://srvld20.noesis.pt/flexdeploy/rest/v1/topology/environment?environmentName=Development | jq '.[] | .environmentId')
          echo "DEPLOYENVID=$DEPLOYENVID"
          
          WFID=$(curl -k -s -u fdadmin:fz#n1vTeHRNQy^9C -H "Content-Type: application/json" -d '{"environmentId":"'"$BUILDENVID"'", "streamId":"'"$STRMID"'"}' -X POST http://srvld20.noesis.pt/flexdeploy/rest/v1/project/$PRJID/build | jq '.workflowRequests[] | .workflowRequestId')
          echo "Workflow ID $WFID"
          CODE_BUILD=$(tail -n1 <<< "$WFID")
          echo "Workflow ID $WFID"
          ST=$(echo $STATUS | tr -d '"')
          if [[ "$ST" == "FAILED" ]]; then
            echo "Build Failed."; exit 1 
          elif [[ "$ST" == "COMPLETED" ]]; then
            echo "Built."; exit 0
          fi
          sleep 10

       # Runs a set of commands using the runners shell
      #- name: Build
      #  run: |
          


